# Generated by Django 4.2.3 on 2023-07-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imgs',
            field=models.ImageField(default='ddd', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
